/*
 * Copyright 2010-2011 Nabeel Mukhtar 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at 
 * 
 *  http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.03 at 06:25:04 PM GMT+05:00 
//


package com.springer.api.schema;

import java.util.ArrayList;
import java.util.List;


/**
 * The Class Indicator.
 */
public class Indicator extends SchemaEntity {

    /** The Constant serialVersionUID. */
	private static final long serialVersionUID = 6564767910412784413L;
	
	/** The name. */
	protected String name;
    
    /** The source. */
    protected Source source;
    
    /** The source note. */
    protected String sourceNote;
    
    /** The source organization. */
    protected String sourceOrganization;
    
    /** The topics. */
    protected List<Topic> topics;
    
    /** The id. */
    protected String id;

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name.
     * 
     * @param value the new name
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the source.
     * 
     * @return the source
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the source.
     * 
     * @param value the new source
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the source note.
     * 
     * @return the source note
     */
    public String getSourceNote() {
        return sourceNote;
    }

    /**
     * Sets the source note.
     * 
     * @param value the new source note
     */
    public void setSourceNote(String value) {
        this.sourceNote = value;
    }

    /**
     * Gets the source organization.
     * 
     * @return the source organization
     */
    public String getSourceOrganization() {
        return sourceOrganization;
    }

    /**
     * Sets the source organization.
     * 
     * @param value the new source organization
     */
    public void setSourceOrganization(String value) {
        this.sourceOrganization = value;
    }

    /**
     * Gets the topics.
     * 
     * @return the topics
     */
    public List<Topic> getTopics() {
    	if (topics == null) {
    		topics = new ArrayList<Topic>();
    	}
        return topics;
    }

    /**
     * Sets the topics.
     * 
     * @param value the new topics
     */
    public void setTopics(List<Topic> value) {
        this.topics = value;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the id.
     * 
     * @param value the new id
     */
    public void setId(String value) {
        this.id = value;
    }
}
